name: Deploy master
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: npm install && npm run build

    - name: Deploy
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist